# Generated by Django 5.2.5 on 2025-09-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simple',
            name='email',
        ),
        migrations.RemoveField(
            model_name='simple',
            name='message',
        ),
        migrations.RemoveField(
            model_name='simple',
            name='submitted_at',
        ),
    ]
