# Generated by Django 5.2.5 on 2025-09-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_simple_email_remove_simple_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
