# Generated by Django 5.2.6 on 2025-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_delete_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
