# Generated by Django 5.2.6 on 2025-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.TextField(max_length=300),
        ),
    ]
