# Generated by Django 5.2.6 on 2025-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='picture',
            field=models.TextField(max_length=300),
        ),
    ]
