# Generated by Django 5.2.6 on 2025-10-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=300),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='picture',
            field=models.URLField(max_length=300),
        ),
    ]
