# Generated by Django 5.2.5 on 2025-10-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_watchlist_auctions_alter_watchlist_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('auctions', 'user')},
        ),
    ]
