# Generated by Django 5.2.5 on 2025-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='auction_open',
            field=models.BooleanField(default=True),
        ),
    ]
